### ISSUE TITLE
App does not load because of CORS

### ISSUE THREAD

**Issue by MPapst** [chunliu/AzureDesignStudio#10]
Current Deployment does not load for me because of an cors error with the stencils:
![image](https://user-images.githubusercontent.com/16494676/169798109-32072df0-de48-408d-b591-e1236e91d048.png)

Also affects local debugging, as cors does not work there either.

**Comment by chunliu** [comment]
From which domain are you trying to load the app? Currently the CORS for the stencil resources is configured for domains:  `https://localhost:7203,https://www.azuredesign.app`. One for local debugging, the other for the actual web app.

**Comment by MPapst** [comment]
Via edge using the link provided on the repo --> https://www.azuredesign.app/

**Comment by bryanrcarlson** [comment]
Seeing the same error:
![image](https://user-images.githubusercontent.com/12533203/169916058-fe619e76-4cb1-4d89-8432-e536bd821df2.png)

Looks like a great tool, so hoping to play around with it!

**Comment by chunliu** [comment]
It may not be a CORS issue, but a network latency issue. Will see if I can improve it. Meanwhile, you may try to reload the page.
