### ISSUE TITLE
Looking for a new logo

### ISSUE THREAD

**Issue by chunliu** [chunliu/AzureDesignStudio#11]
The current logo is a quick draft that I created several months ago. It's not a perfect one as I am not good at the visual design of icons and logos. I am looking for a better one to replace it.

**Comment by Developing-Developer2019** [comment]
Any ideas on what you want the logo to look like?

**Comment by chunliu** [comment]
In my imagination, it would be something simple and modern, and easy to be recognized and remembered. It would make people associate it with Azure easily... I'm open to any suggestions ...

**Comment by Developing-Developer2019** [comment]
What comes to mind for me, is that it shouldn't be the same as Azure's logo in case Azure decides to change theirs then it would be unlinked. Maybe something along the lines of a Cloud type logo with scaffolding with a spanner/paintbrush to edge towards design and set in the cloud

**Comment by dluc** [comment]
what about an architect thinking about a cloud?
![image](https://user-images.githubusercontent.com/371009/170388282-b2b1e61d-15c3-4710-9b3f-c818310c7370.png)
![image](https://user-images.githubusercontent.com/371009/170388296-5817e634-6989-4c6a-8551-4e89a4fa6123.png)

**Comment by chunliu** [comment]
Thanks for the ideas @Developing-Developer2019 and @dluc .

**Comment by PaulTozer** [comment]
What about something like the following. Using the parts of Azure icon libraries

 ![image](https://user-images.githubusercontent.com/45483044/187680777-f15b930b-a1d6-4031-94de-e573bace4434.png)
