### ISSUE TITLE
Azure Design with Infrastructure Code Workflow

### ISSUE THREAD

**Issue by GeorgeS2019** [chunliu/AzureDesignStudio#15]
@chunliu 

We are thinking how to [repurpose ](https://github.com/elsa-workflows/elsa-studio/discussions/10#discussion-5466426)your Blazor.Diagram implementation to the .NET Workflow Designer

##### [reference](https://github.com/elsa-workflows/elsa-studio/issues/2)

**Comment by chunliu** [comment]
Feel free to do it. Blazor.Diagram is an open source project that I forked from https://github.com/Blazor-Diagrams/Blazor.Diagrams.
