### ISSUE TITLE
Azure Design Studio Load Error

### ISSUE THREAD

**Issue by numericscloud** [chunliu/AzureDesignStudio#16]
![DesignStudioLoadError](https://github.com/chunliu/AzureDesignStudio/assets/19992454/43aaac67-ca4e-40bd-970e-92ae64cffded)

On first load the design studio does not load.

Steps to reproduce:
1. Clone repo in VS2022
2. Build project
3. Set AzureDesignStudio.Server as the startup project in Visual Studio 2022.
4. Run the project

**Comment by chunliu** [comment]
The project needs some supporting services from Azure. You can check the configuration needed in `src/AzureDesignStudio.Server/appsettings.json` and `/src/AzureDesignStudio/wwwroot/appsettings.json`.
