### ISSUE TITLE
Can't build docker image

### ISSUE THREAD

**Issue by 00yAyA0** [chunliu/AzureDesignStudio#17]
When i run the script "DockerBuild.ps1" to build the image, i get the following error:

Get Nerdbank Git Version.
Directory.Build.target has been generated. Nerdbank Version: 0.4.33-g4dbcccdd5c
[+] Building 11.1s (20/24)                                                                                                                                                                          docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 1.64kB                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 382B                                                                                                                                                                             0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:7.0                                                                                                                                             0.4s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0                                                                                                                                          0.4s
 => [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:567be43cf97d21523845af3cadf576517bc541cbf18d4a5d11b36873d2b025c4                                                                               0.0s
 => [build  1/14] FROM mcr.microsoft.com/dotnet/sdk:7.0@sha256:e882cf3bbeadd42cbe42ed5a76b06379564b285cc16ad2f1ee5e45ebe64b8cb1                                                                               0.0s
 => [internal] load build context                                                                                                                                                                             0.2s
 => => transferring context: 351.65kB                                                                                                                                                                         0.2s
 => CACHED [build  2/14] WORKDIR /src                                                                                                                                                                         0.0s
 => CACHED [build  3/14] COPY [AzureDesignStudio.Server/AzureDesignStudio.Server.csproj, AzureDesignStudio.Server/]                                                                                           0.0s
 => CACHED [build  4/14] COPY [AzureDesignStudio.SharedModels/AzureDesignStudio.SharedModels.csproj, AzureDesignStudio.SharedModels/]                                                                         0.0s
 => CACHED [build  5/14] COPY [AzureDesignStudio/AzureDesignStudio.csproj, AzureDesignStudio/]                                                                                                                0.0s
 => CACHED [build  6/14] COPY [AzureDesignStudio.Core/AzureDesignStudio.Core.csproj, AzureDesignStudio.Core/]                                                                                                 0.0s
 => CACHED [build  7/14] COPY [AzureDesignStudio.AzureResources/AzureDesignStudio.AzureResources.csproj, AzureDesignStudio.AzureResources/]                                                                   0.0s
 => CACHED [build  8/14] COPY [Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj, Blazor.Diagrams/src/Blazor.Diagrams.Core/]                                                               0.0s
 => CACHED [build  9/14] COPY [Blazor.Diagrams/src/Blazor.Diagrams/Blazor.Diagrams.csproj, Blazor.Diagrams/src/Blazor.Diagrams/]                                                                              0.0s
 => CACHED [build 10/14] COPY [AzureDesignStudio.SourceGeneration/AzureDesignStudio.SourceGeneration.csproj, AzureDesignStudio.SourceGeneration/]                                                             0.0s
 => CACHED [build 11/14] RUN dotnet restore "AzureDesignStudio.Server/AzureDesignStudio.Server.csproj"                                                                                                        0.0s
 => CACHED [build 12/14] COPY . .                                                                                                                                                                             0.0s
 => CACHED [build 13/14] WORKDIR /src/AzureDesignStudio.Server                                                                                                                                                0.0s
 => ERROR [build 14/14] RUN dotnet build "AzureDesignStudio.Server.csproj" -c Release -o /app/build                                                                                                          10.5s
------
 > [build 14/14] RUN dotnet build "AzureDesignStudio.Server.csproj" -c Release -o /app/build:
0.472 MSBuild version 17.7.4+3ebbd7c49 for .NET
1.238   Determining projects to restore...
2.793   All projects are up-to-date for restore.
5.802 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Extensions/BaseLinkModelExtensions.cs(59,61): warning CS8602: Dereference of a possibly null reference. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
5.802 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Models/NodeModel.cs(18,16): warning CS8618: Non-nullable property 'Title' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
5.802 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Models/NodeModel.cs(25,16): warning CS8618: Non-nullable property 'Title' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
5.802 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Extensions/BaseLinkModelExtensions.cs(103,16): warning CS8602: Dereference of a possibly null reference. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
5.802 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Extensions/BaseLinkModelExtensions.cs(106,16): warning CS8602: Dereference of a possibly null reference. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
5.849   Blazor.Diagrams.Core -> /app/build/Blazor.Diagrams.Core.dll
5.850   AzureDesignStudio.SharedModels -> /app/build/AzureDesignStudio.SharedModels.dll
5.960   AzureDesignStudio.AzureResources -> /app/build/AzureDesignStudio.AzureResources.dll
6.136   The package Z.Blazor.Diagrams.Core.2.1.6 is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are important.
6.136   Successfully created package '/app/build/Z.Blazor.Diagrams.Core.2.1.6.nupkg'.
7.214   Blazor.Diagrams -> /app/build/Blazor.Diagrams.dll
7.523   The package Z.Blazor.Diagrams.2.1.6 is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are important.
7.523   Successfully created package '/app/build/Z.Blazor.Diagrams.2.1.6.nupkg'.
8.463   AzureDesignStudio.SourceGeneration -> /app/build/AzureDesignStudio.SourceGeneration.dll
10.36 /src/AzureDesignStudio.Core/DataModelFactory.cs(76,17): error CS0117: 'LinkModel' does not contain a definition for 'StrokeStyle' [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.36 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(16,18): error CS1061: 'PortModel' does not contain a definition for 'OnLinkAdded' and no accessible extension method 'OnLinkAdded' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.36 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(17,18): error CS1061: 'PortModel' does not contain a definition for 'OnLinkRemoved' and no accessible extension method 'OnLinkRemoved' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.36 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(20,17): error CS1061: 'PortModel' does not contain a definition for 'OnLinkAdded' and no accessible extension method 'OnLinkAdded' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.36 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(21,17): error CS1061: 'PortModel' does not contain a definition for 'OnLinkRemoved' and no accessible extension method 'OnLinkRemoved' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.36 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(24,19): error CS1061: 'PortModel' does not contain a definition for 'OnLinkAdded' and no accessible extension method 'OnLinkAdded' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.36 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(25,19): error CS1061: 'PortModel' does not contain a definition for 'OnLinkRemoved' and no accessible extension method 'OnLinkRemoved' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.36 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(28,20): error CS1061: 'PortModel' does not contain a definition for 'OnLinkAdded' and no accessible extension method 'OnLinkAdded' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.36 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(29,20): error CS1061: 'PortModel' does not contain a definition for 'OnLinkRemoved' and no accessible extension method 'OnLinkRemoved' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.36 /src/AzureDesignStudio.Core/DTO/AzureNodeProfile.cs(15,37): error CS0200: Property or indexer 'NodeModel.Group' cannot be assigned to -- it is read only [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40
10.40 Build FAILED.
10.40
10.40 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Extensions/BaseLinkModelExtensions.cs(59,61): warning CS8602: Dereference of a possibly null reference. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
10.40 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Models/NodeModel.cs(18,16): warning CS8618: Non-nullable property 'Title' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
10.40 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Models/NodeModel.cs(25,16): warning CS8618: Non-nullable property 'Title' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
10.40 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Extensions/BaseLinkModelExtensions.cs(103,16): warning CS8602: Dereference of a possibly null reference. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
10.40 /src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Extensions/BaseLinkModelExtensions.cs(106,16): warning CS8602: Dereference of a possibly null reference. [/src/Blazor.Diagrams/src/Blazor.Diagrams.Core/Blazor.Diagrams.Core.csproj]
10.40 /src/AzureDesignStudio.Core/DataModelFactory.cs(76,17): error CS0117: 'LinkModel' does not contain a definition for 'StrokeStyle' [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(16,18): error CS1061: 'PortModel' does not contain a definition for 'OnLinkAdded' and no accessible extension method 'OnLinkAdded' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(17,18): error CS1061: 'PortModel' does not contain a definition for 'OnLinkRemoved' and no accessible extension method 'OnLinkRemoved' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(20,17): error CS1061: 'PortModel' does not contain a definition for 'OnLinkAdded' and no accessible extension method 'OnLinkAdded' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(21,17): error CS1061: 'PortModel' does not contain a definition for 'OnLinkRemoved' and no accessible extension method 'OnLinkRemoved' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(24,19): error CS1061: 'PortModel' does not contain a definition for 'OnLinkAdded' and no accessible extension method 'OnLinkAdded' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(25,19): error CS1061: 'PortModel' does not contain a definition for 'OnLinkRemoved' and no accessible extension method 'OnLinkRemoved' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(28,20): error CS1061: 'PortModel' does not contain a definition for 'OnLinkAdded' and no accessible extension method 'OnLinkAdded' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40 /src/AzureDesignStudio.Core/Network/AppGatewayModel.cs(29,20): error CS1061: 'PortModel' does not contain a definition for 'OnLinkRemoved' and no accessible extension method 'OnLinkRemoved' accepting a first argument of type 'PortModel' could be found (are you missing a using directive or an assembly reference?) [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40 /src/AzureDesignStudio.Core/DTO/AzureNodeProfile.cs(15,37): error CS0200: Property or indexer 'NodeModel.Group' cannot be assigned to -- it is read only [/src/AzureDesignStudio.Core/AzureDesignStudio.Core.csproj]
10.40     5 Warning(s)
10.40     10 Error(s)
10.40
10.40 Time Elapsed 00:00:09.73
------
Dockerfile:21
--------------------
  19 |     COPY . .
  20 |     WORKDIR "/src/AzureDesignStudio.Server"
  21 | >>> RUN dotnet build "AzureDesignStudio.Server.csproj" -c Release -o /app/build
  22 |
  23 |     FROM build AS publish
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet build \"AzureDesignStudio.Server.csproj\" -c Release -o /app/build" did not complete successfully: exit code: 1
Build completed.

**Comment by chunliu** [comment]
Did you follow the readme to clone the repo? `git clone --recursive https://github.com/chunliu/AzureDesignStudio.git`

**Comment by 00yAyA0** [comment]
Hello,

Thank you for your response.
I executed this cmd and the build was successful. But when I create a container based on the built image, i got this error:

2023-12-16 13:46:07 Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
2023-12-16 13:46:07    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
2023-12-16 13:46:07    at System.Uri..ctor(String uriString)
2023-12-16 13:46:07    at Program.<Main>$(String[] args) in /src/AzureDesignStudio.Server/Program.cs:line 27

**Comment by chunliu** [comment]
The code has some dependencies on other Azure services. You need to have those dependencies configured correctly before the code can run properly.
